"""Add player tournaments

Revision ID: 13d2168a65ea
Revises: 453b594348b8
Create Date: 2026-03-27 16:21:15.143922

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = '13d2168a65ea'
down_revision = '453b594348b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_tournament',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('missed_cut', sa.Boolean(), nullable=False),
    sa.Column('withdrawn', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['app.player.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['app.tournament.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_tournament', schema='app')
    # ### end Alembic commands ###
