"""Add player pool tiers

Revision ID: 2e2ad08515a3
Revises: 13d2168a65ea
Create Date: 2026-03-27 17:04:29.213081

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2e2ad08515a3'
down_revision = '13d2168a65ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_pool_tier',
    sa.Column('player_tournament_id', sa.Uuid(), nullable=False),
    sa.Column('pool_tier_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_tournament_id'], ['app.player_tournament.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pool_tier_id'], ['app.pool_tier.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_pool_tier', schema='app')
    # ### end Alembic commands ###
